<?php

function hosting_clone_hosting_tasks() {
  $options = array();

  $options['site']['clone'] = array(
    'title' => t('Clone'),
    'description' => t('Make a copy of a site.'),
    'weight' => 5,
    'dialog' => TRUE
  );
  return $options;
}

function hosting_clone_perm() {
  return array(
    'create clone task',
  );
}

function hosting_task_clone_form_validate($form, &$form_state) {
  $site = $form['parameters']['#node'];

  $url = strtolower(trim($form_state['values']['parameters']['new_uri'])); // domain names are case-insensitive
  if ($url == $site->title) {
    form_set_error('new_uri', t("To clone a site you need to specify a new Domain name to clone it to."));
  }
  else {
    hosting_task_migrate_form_validate($form, $form_state);
  }
  // Although the following is more or less the same in the hosting_task_migrate_form_validate(),
  // it's repeated here but the difference is we check if the alias is already in use *anywhere*, 
  // rather than make an exception for the current site node (which is allowed to retain its aliases)
  if ($form_state['values']['parameters']['aliases']) {
    $aliases = explode("\n", $form_state['values']['parameters']['aliases']);
    foreach ($aliases as $alias) {
      if ($alias = trim($alias)) {
        if (!hosting_domain_allowed($alias)) {
          form_set_error('aliases', t('The domain name @alias is already in use', array('@alias' => $alias)));
        }
      }
    }
  }

}

function hosting_clone_theme($existing, $type, $theme, $path) {
  return array('hosting_task_clone_form' => array('arguments' => array('form' => NULL)));
}

function hosting_task_clone_form($node) {
  $form = hosting_task_migrate_form($node);
  $form['new_uri']['#description'] = t('The new domain name of the clone site.');
  return $form;
}

function theme_hosting_task_clone_form(&$form) {
  return theme_hosting_task_migrate_form($form);
}

